name: sidekick
description: Flutter Version Manager.

publish_to: "none"

version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  animations: ^2.0.0
  async: ^2.6.1
  date_time_format: ^2.0.1
  dio: ^4.0.0
  file_selector: ^0.8.2
  file_selector_linux: ^0.0.2
  file_selector_macos: ^0.0.4
  file_selector_windows: ^0.0.2
  filesize: ^2.0.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.17.0
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.0.0
  fvm: ^2.2.3
  google_fonts: ^2.1.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  hooks_riverpod: ^0.14.0+4
  i18next:
    git: https://github.com/Ahmadre/i18next.git
  material_design_icons_flutter: ^5.0.5955-rc.1
  material_floating_search_bar: ^0.3.4
  oktoast: ^3.0.0
  open_file: ^3.2.1
  path_provider: 2.0.1
  pub_api_client: ^2.0.5
  pubspec_parse: ^1.0.0
  responsive_grid: ^2.0.0
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.4
  watcher: ^1.0.0
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  build_runner: ^2.0.3
  build_version: ^2.0.3
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  msix: ^2.1.1
  pedantic: ^1.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - localizations/ar-SA/
    - localizations/de-DE/
    - localizations/en-GB/
    - localizations/en-US/
    - localizations/es-ES/
flutter_intl:
  enabled: true
