name: sidekick
description: Flutter Version Manager.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fvm: ^2.0.5

  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  animations: ^2.0.0
  async: ^2.6.1
  date_time_format: ^2.0.1

  filesize: ^2.0.1
  flutter_cache: ^0.1.0
  flutter_hooks: ^0.17.0
  flutter_spinkit: ^5.0.0
  github: ^8.1.0
  google_fonts: ^2.1.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  hooks_riverpod: ^0.14.0+4
  list_ext: ^1.0.2
  material_design_icons_flutter: ^4.0.5955
  material_floating_search_bar: ^0.3.4
  oktoast: ^3.0.0
  path_provider: ^2.0.1
  pub_api_client: ^2.0.5
  responsive_grid: ^2.0.0
  truncate: ^3.0.1
  url_launcher: ^6.0.4
  watcher: ^1.0.0
  open_file: ^3.2.1
  pubspec_parse: ^1.0.0
  file_selector: ^0.8.2
  file_selector_linux: ^0.0.2
  file_selector_macos: ^0.0.4
  file_selector_windows: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.3
  effective_dart: ^1.3.1
  hive_generator: ^1.1.0
  msix: ^2.1.1
  build_version: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
