name: sidekick
description: Flutter Version Manager.

publish_to: "none"

version: 1.1.2

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animations: ^2.0.2
  async: ^2.6.1
  bitsdojo_window: ^0.1.5
  collection: ^1.17.1
  date_time_format: ^2.0.1
  dio: ^5.1.2
  file_selector: ^1.0.3
  file_selector_linux: ^0.9.1+3
  file_selector_macos: ^0.9.2
  file_selector_windows: ^0.9.1+4
  filesize: ^2.0.1
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.1
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.0.0
  fvm: ^2.4.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  hooks_riverpod: ^2.1.3
  http: ^1.2.2
  i18next:
    git: https://github.com/Ahmadre/i18next.git
  intl: 0.19.0
  material_design_icons_flutter: ^6.0.7096
  material_floating_search_bar_2: ^0.5.0
  oktoast: ^3.2.0
  open_file:
    git:
      url: https://github.com/crazecoder/open_file
      path: open_file
  path: ^1.8.3
  path_provider: ^2.0.1
  pool: ^1.5.1
  pub_api_client: ^2.0.5
  pub_semver: ^2.1.4
  pubspec_parse: ^1.0.0
  responsive_grid: ^2.0.0
  shared_preferences: ^2.0.6
  system_info2: ^4.0.0
  url_launcher: ^6.0.4
  watcher: ^1.0.0
  window_manager: ">=0.2.3"
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  build_runner: ^2.4.6
  build_version: ^2.1.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  msix: ^3.16.0

flutter:
  uses-material-design: true
  assets:
    - localizations/ar-SA/
    - localizations/bn-BD/
    - localizations/de-DE/
    - localizations/en-GB/
    - localizations/en-US/
    - localizations/es-ES/
    - localizations/sv-SE/
    - localizations/zh-CN/
    - localizations/zh-TW/
    - localizations/ko-KR/
    - localizations/ja-JP/
    - localizations/pl-PL/
    - localizations/pt-BR/
    - localizations/it-IT/
    - localizations/uk-UA/
    - localizations/uz-CY/
    - localizations/uz-LA/
    - localizations/ru-RU/
    - localizations/hi-IN/
    - localizations/id-ID/
    - localizations/fr-FR/
    - localizations/tr-TR/

flutter_intl:
  enabled: true

dependency_overrides:
  cli_util: ^0.4.0

